# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 478c88d784d9ccd665e0016927c2a4c31587f16a82fd416d6bfe82680707d84c84ae71972fa635cd1e6338c07523993946b801618ca881b80ff2d91d2cb5ff23

test:
  secret_key_base: 726077eb8427a372aa90f8122e465756aadc70ab993c90f682d356cb5812b3c7fc9d371d5c32f5939be12b77d4bc17a88f50f4eccdbd91b2d46b31d050873c00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
